FROM centos:6.8
LABEL maintainer="Nils Vogels <n.vogels@aves-it.nl>"
RUN yum install -y \
    wget \
    libxslt-devel \
    openldap-devel \
    perl \
    pkgconfig \
    db4-devel \
    system-logos \
    perl \
    initscripts \
    libxslt \
    mailcap \
    gcc \
    gcc-c++ \
    automake \
    memcached \
    libaio \
    libX11 \
    libpng-devel \
    cairo-devel \
    readline-devel \
    crontabs
